version: '3'
services:
    redis:
        image: redis:latest
        container_name: cur_redis01
        ports:
            - '6379:6379'
    mongo:
        image: 'mongo:5.0.5'
        container_name: cur_mongo
        ports:
            - '27017:27017'
    django_web:
        build:
            context: .
            dockerfile: Dockerfile-prod
        container_name: cur_django
        ports:
            - "8000:8000"
        volumes:
            - ./src:/app
            - static_data:/vol/web
        env_file:
            - .env
        command: sh -c "/scripts/prod-entrypoint.sh"
        # command: sh -c "python manage.py runserver 0.0.0.0:8000"
        depends_on:
            - redis
            - mongo
    celery_worker:
        build:
            context: .
            dockerfile: Dockerfile-prod
        container_name: cur_worker01
        volumes:
            - ./src:/app
        env_file:
            - .env
        command: celery -A cur_extractor worker -l INFO
        depends_on:
            - redis
            - mongo

    celery_beat:
        build:
            context: .
            dockerfile: Dockerfile-prod
        container_name: cur_beat
        volumes:
            - ./src:/app
        env_file:
            - .env
        command: celery -A cur_extractor beat -l INFO
        depends_on:
            - redis
            - mongo

    proxy:
        build:
            context: ./proxy
        container_name: proxy
        volumes:
            - static_data:/vol/static
        ports:
            - "8080:8080"
        depends_on:
            - django_web


volumes:
    static_data:
