# Generated by Django 4.0.1 on 2022-02-09 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedAccount',
            fields=[
                ('account_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='PayerAccount',
            fields=[
                ('account_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'payer',
            },
        ),
        migrations.CreateModel(
            name='StorageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_name', models.CharField(max_length=63)),
                ('prefix', models.CharField(blank=True, max_length=1000)),
                ('access_key', models.CharField(max_length=128)),
                ('secret_key', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'storage_info',
            },
        ),
        migrations.CreateModel(
            name='ReportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('prefix', models.CharField(max_length=128)),
                ('access_key', models.CharField(max_length=128)),
                ('secret_key', models.CharField(max_length=1024)),
                ('bucket_name', models.CharField(max_length=63)),
                ('accounts', models.ManyToManyField(blank=True, to='accounts.LinkedAccount')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.payeraccount')),
            ],
            options={
                'db_table': 'report_info',
            },
        ),
        migrations.AddField(
            model_name='payeraccount',
            name='storage_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.storageinfo'),
        ),
        migrations.AddField(
            model_name='linkedaccount',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.payeraccount'),
        ),
    ]
