# Generated by Django 4.0.1 on 2022-02-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinfo',
            name='blended',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reportinfo',
            name='credit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reportinfo',
            name='refund',
            field=models.BooleanField(default=True),
        ),
    ]
