# Generated by Django 4.0.1 on 2022-03-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_reportinfo_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinfo',
            name='external_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='storageinfo',
            name='external_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
